#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    fastfetch
    echo "${I_OK}    Install base desktop"
    sudo apk add --no-cache xterm mint-y-theme\
    font-terminus font-dejavu\
    mint-y-icons dbus elogind polkit-elogind polkit-lang gvfs udisks2 mesa-gles 
fi