#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    echo "${I_OK}    Configuring lightdm-gtk-greeter"
    wget --no-cache -O /etc/lightdm/lightdm-gtk-greeter.conf ${URLgithub}/global/lightdm-gtk-greeter.conf

    mkdir -p /usr/share/pixmaps/
    adduser $(getent passwd 1000 | cut -d: -f1) plugdev
    wget --no-cache -O /usr/share/applications/my-github.desktop ${URLgithub}/global/github.desktop
    wget --no-cache -O /usr/share/applications/my-afimpelelnerd.desktop ${URLgithub}/global/afimpelelnerd.desktop
    wget --no-cache -O /usr/share/applications/my-youtube.desktop ${URLgithub}/global/youtube.desktop
    wget  -O - https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/Desktop/cli.sh | sh

    wget --no-cache -O /etc/NetworkManager/NetworkManager.conf ${URLgithub}/global/NetworkManager/NetworkManager.conf 
    wget --no-cache -O /etc/NetworkManager/conf.d/any-user.conf ${URLgithub}/global/NetworkManager/conf.d/any-user.conf
    wget --no-cache -O /etc/security/limits.d/audio.conf ${URLgithub}/global/security/audio.conf 

    echo "${I_OK}    Downloading ICONS"
    wget --no-cache -O /usr/share/pixmaps/youtube.svg ${URLgithub}/global/youtube.svg
    wget --no-cache -O /usr/share/pixmaps/github.svg ${URLgithub}/global/github.svg
    wget --no-cache -O /usr/share/pixmaps/youtube.png ${URLgithub}/global/youtube.png
    wget --no-cache -O /usr/share/pixmaps/github.png ${URLgithub}/global/github.png
    wget --no-cache -O /usr/share/pixmaps/alpine.png ${URLgithub}/global/alpine.png
    wget --no-cache -O /usr/share/pixmaps/afimpelelnerd.png ${URLgithub}/global/afimpelelnerd.png

    echo "${I_OK}    Downloading wallpapers"
    mkdir -p /usr/share/backgrounds
    wget --no-cache -O /usr/share/backgrounds/wallpaper.jpg ${URLgithub}/assets/wallpaper.jpg?raw=true
    wget --no-cache -O /usr/share/backgrounds/wallpaper-1.jpg ${URLgithub}/assets/wallpaper-1.jpg?raw=true
    wget --no-cache -O /usr/share/backgrounds/wallpaper-2.jpg ${URLgithub}/assets/wallpaper-2.jpg?raw=true
    wget --no-cache -O /usr/share/backgrounds/wallpaper-3.jpg ${URLgithub}/assets/wallpaper-3.jpg?raw=true
    wget --no-cache -O /usr/share/backgrounds/wallpaper-4.jpg ${URLgithub}/assets/wallpaper-4.jpg?raw=true

    echo "Install Date: $(date)" >> /etc/motd
    chmod 777 /usr/share/backgrounds/* -R
    chmod 777 /usr/share/pixmaps/* -R
    chmod 777 /usr/share/applications/my-* -R
fi