#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"

if [ $UUID == 0 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    echo "${I_OK}    Configuring user ..."
    mkdir -p ~/.config/rofi
    mkdir -p ~/.config/neofetch
    curl -H 'Pragma: no-cache' -L https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/neofetch.conf > ~/.config/neofetch/config.conf
    curl -H 'Pragma: no-cache' https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/rofi.rasi > ~/.config/rofi/config.rasi
    curl -H 'Pragma: no-cache' https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/bashrc > ~/.bashrc
    curl -H 'Pragma: no-cache' https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/Xdefaults > ~/.Xdefaults
    curl -H 'Pragma: no-cache' https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/Xresources > ~/.Xresources
fi