#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    echo "${I_OK}    BACKUP: Repositories"
    cp /etc/apk/repositories /etc/apk/repositories_old
    mv /etc/profile.d/color_prompt.sh.disabled /etc/profile.d/color_prompt.sh

    echo "${I_OK}    BASH: Alias"
    echo "
    #!/bin/bash
    export LS_OPTIONS='--color=auto';
    alias tailf='tail --follow'
    alias ls='ls $LS_OPTIONS'
    alias dir='lsd'
    alias ll='lsd -lh'
    alias la='lsd -lhA'
    " > /etc/profile.d/alias-completion.sh

    echo "${I_OK}    BASH: Completion"
    echo 'if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${BASH_COMPLETION_VERSINFO-}" = x ]; then
        # Check for recent enough version of bash.
        if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
            [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
            [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
                . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
            if shopt -q progcomp && [ -r /usr/share/bash-completion/bash_completion ]; then
                # Source completion code.
                . /usr/share/bash-completion/bash_completion
            fi
        fi
    fi' > /etc/profile.d/bash-completion.sh

    url=$(more /etc/apk/repositories | grep http | grep -v '^#' | head -n 1)
    repositories_url="${url%/*/*}"
    echo "${I_OK}    Repositories: ${repositories_url}/edge | { main, community & testing }"
    echo "${repositories_url}/edge/main" > /etc/apk/repositories
    echo "${repositories_url}/edge/community" >> /etc/apk/repositories
    echo "${repositories_url}/edge/testing" >> /etc/apk/repositories

    apk update 
    apk add --no-cache nano lsd git mc bash zsh htop curl btop lsblk bash-completion lsb-release-minimal openssl jq fastfetch

    echo "${I_OK}    CHANGE: ASH to BASH"
    sed -i 's/\/bin\/ash/\/bin\/bash/g' /etc/passwd

    echo "${I_OK}    ADD: Toolkit"
    wget --no-cache -O /usr/bin/upgrade-system https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/upgrade-system 
    wget --no-cache -O /usr/bin/upgrade-system-poweroff https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/upgrade-system-poweroff 
    wget --no-cache -O /usr/bin/upgrade-system-reboot https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/upgrade-system-reboot 
    wget --no-cache -O /usr/bin/get-ip-address ${URLgithub}/global/get-ip-address 
    wget --no-cache -O /usr/bin/update-time ${URLgithub}/global/update-time
    wget --no-cache -O /usr/bin/login-info ${URLgithub}/global/login-info 

    chmod 777 /usr/bin/login-info
    chmod 777 /usr/bin/get-ip-address
    chmod 777 /usr/bin/upgrade-system* -R
    chmod 777 /usr/bin/update-t* -R
    chmod 777 /etc/profile.d/*.sh

    echo "${I_OK}    END: $(date)"
    upgrade-system-reboot
fi