#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"


NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    cp /etc/apk/repositories /etc/apk/repositories_old
    cp /etc/profile.d/color_prompt.sh.disabled /etc/profile.d/color_prompt.sh

    echo 'if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${BASH_COMPLETION_VERSINFO-}" = x ]; then

        # Check for recent enough version of bash.
        if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
            [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
            [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
                . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
            if shopt -q progcomp && [ -r /usr/share/bash-completion/bash_completion ]; then
                # Source completion code.
                . /usr/share/bash-completion/bash_completion
            fi
        fi

    fi' > /etc/profile.d/bash-completion.sh

    echo "
    #!/bin/bash
    export LS_OPTIONS='--color=auto';
    alias tailf='tail --follow'
    alias ls='ls $LS_OPTIONS'
    alias dir='lsd'
    alias ll='lsd -lh'
    alias la='lsd -lhA'
    " > /etc/profile.d/alias-completion.sh
    chmod 777 /etc/profile.d/*.sh

    echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

    apk update 
    apk add --no-cache nano lsd git mc bash zsh htop neofetch curl btop sudo lsblk bash-completion
    echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/wheel
    echo "%wheel ALL=(ALL) NOPASSWD: /sbin/poweroff, /sbin/reboot, /sbin/shutdown, /usr/bin/upgrade-syste*" >> /etc/sudoers.d/wheel
    sed -i 's/\/bin\/ash/\/bin\/bash/g' /etc/passwd
    mkdir -p /etc/neofetch
    
    curl -H 'Pragma: no-cache' -L https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/upgrade-system > /usr/bin/upgrade-system
    curl -H 'Pragma: no-cache' -L https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/upgrade-system-poweroff > /usr/bin/upgrade-system-poweroff
    curl -H 'Pragma: no-cache' -L https://raw.githubusercontent.com/afimpel/upgrade-system-alpine/main/upgrade-system-reboot > /usr/bin/upgrade-system-reboot
    curl -H 'Pragma: no-cache' https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/get-ip-address > /usr/bin/get-ip-address 
    curl -H 'Pragma: no-cache' -L https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/neofetch.conf > /etc/neofetch/config.conf

    chmod 777 /usr/bin/get-ip-address
    chmod 777 /usr/bin/upgrade-system* -R
    adduser $(getent passwd 1000 | cut -d: -f1) wheel

    neofetch
    upgrade-system-reboot
fi