#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    echo "${I_OK}    Configuring lightdm-gtk-greeter"
    mkdir -p /usr/share/xsessions
    sleep 2s
    curl -H 'Pragma: no-cache' ${URLgithub}/fluxbox/gtk-config/fluxbox.desktop > /usr/share/xsessions/fluxbox.desktop
    curl -H 'Pragma: no-cache' ${URLgithub}/fluxbox/gtk-config/lightdm.conf > /etc/lightdm/lightdm.conf
    chmod 777 /usr/share/xsessions -R
    cat /usr/share/xsessions/fluxbox.desktop
fi