#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    adduser $(getent passwd 1000 | cut -d: -f1) audio
    echo "${I_OK}    Configuring lightdm-gtk-greeter"
    mkdir -p /usr/share/xsessions
    sleep 2s
    wget --no-cache -O /usr/share/xsessions/fluxbox.desktop ${URLgithub}/fluxbox/gtk-config/fluxbox.desktop
    wget --no-cache -O /etc/lightdm/lightdm.conf ${URLgithub}/fluxbox/gtk-config/lightdm.conf
    chmod 777 /usr/share/xsessions -R
    cat /usr/share/xsessions/fluxbox.desktop
fi