#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID != 1000 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    sudo setup-xorg-base 
    echo "${I_OK}    **** install packages ****" 
    sudo apk add --no-cache fluxbox feh tint2 pcmanfm pcmanfm-lang alsa-utils alsaconf\
        xterm lightdm-gtk-greeter lightdm-gtk-greeter-lang mint-y-theme adwaita-icon-theme\
        mint-y-icons dbus elogind polkit-elogind gvfs udisks2 mousepad mousepad-lang rofi\
        dmenu font-fira-code font-fira-code-nerd font-fira-mono-nerd font-jetbrains-mono-nerd\
        font-hack-nerd nerd-fonts networkmanager-wifi networkmanager networkmanager-lang\
        network-manager-applet firefox tilix pcmanfm pcmanfm-lang

    sudo rc-update add dbus
    sudo rc-update add lightdm
    sudo rc-update add elogind
    sudo rc-update del networking boot
    sudo rc-update del wpa_supplicant boot
    sudo rc-update add networkmanager
    sudo rc-update add alsa

    echo "${I_OK}    **** application tweaks ****"
    mkdir -p ~/.fluxbox/
    mkdir -p ~/script/

    wget --no-cache -O - ${URLgithub}/global/install-as-user | bash
    mkdir -p ~/.config/tint2
    mkdir -p ~/.config/gtk-3.0
    mkdir -p ~/Templates
    wget --no-cache -O ~/.fluxbox/apps ${URLgithub}/fluxbox/user-config/fluxbox/apps
    wget --no-cache -O ~/.fluxbox/init ${URLgithub}/fluxbox/user-config/fluxbox/init
    wget --no-cache -O ~/.fluxbox/keys ${URLgithub}/fluxbox/user-config/fluxbox/keys
    wget --no-cache -O ~/.fluxbox/lastwallpaper ${URLgithub}/fluxbox/user-config/fluxbox/lastwallpaper
    wget --no-cache -O ~/.fluxbox/menuconfig ${URLgithub}/fluxbox/user-config/fluxbox/menuconfig
    wget --no-cache -O ~/.fluxbox/startup ${URLgithub}/fluxbox/user-config/fluxbox/startup
    wget --no-cache -O ~/.fluxbox/usermenu ${URLgithub}/fluxbox/user-config/fluxbox/usermenu
    chmod 777 -Rv ~/.fluxbox/*
    wget --no-cache -O ~/script/my-rofi.sh ${URLgithub}/fluxbox/script/my-rofi.sh
    wget --no-cache -O ~/script/poweroff.sh ${URLgithub}/fluxbox/script/poweroff.sh
    chmod 777 -Rv ~/script/*
    wget --no-cache -O ~/.gtkrc-2.0 ${URLgithub}/fluxbox/user-config/gtkrc-2.0
    wget --no-cache -O ~/.config/gtk-3.0/settings.ini ${URLgithub}/fluxbox/user-config/config/gtk-3.0/settings.ini
    wget --no-cache -O ~/.config/tint2/fluxbox.tint2rc ${URLgithub}/fluxbox/user-config/config/tint2/fluxbox.tint2rc
    wget --no-cache -O ~/.config/tint2/tint2rc ${URLgithub}/fluxbox/user-config/config/tint2/fluxbox.tint2rc
    wget --no-cache -O - ${URLgithub}/global/lightdm-as-root | sudo bash
    wget --no-cache -O - ${URLgithub}/fluxbox/install-as-fluxbox | sudo bash
    sudo wget --no-cache -O /etc/motd ${URLgithub}/fluxbox/motd
    wget --no-cache -O - ${URLgithub}/global/install-as-root | sudo bash
    echo "${I_OK}    **** cleanup ****"
    rm -rvf /config/.cache/* /tmp/*
 
    sudo upgrade-system-reboot
fi