#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID != 1000 ]; then
        echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
        exit 1;
else
    sudo setup-xorg-base 
    echo "${I_OK}    bspwm setup script with lightdm"
    sudo apk add --no-cache bspwm sxhkd lightdm-gtk-greeter rxvt-unicode feh picom setxkbmap font-fira-code font-ubuntu libva-glx rofi polybar ranger htop xterm firefox mousepad pulseaudio pulseaudio-alsa alsa-plugins-pulse pulseaudio-utils pavucontrol xcalc
    # Creates main config directory
    echo "${I_OK}    Creating config directory"
    mkdir ~/.config
    # Creates subdirectories
    echo "${I_OK}    Creating bspwm, sxhkd, picom and polybar subdirectories"
    mkdir ~/.config/bspwm
    mkdir ~/.config/sxhkd
    mkdir ~/.config/picom
    mkdir ~/.config/polybar
    mkdir ~/.config/rofi

    #lightdm-gtk-greeter
    #polybar
    echo "${I_OK}    Creating polybar files"
    rm ~/.config/polybar/launch.sh
    wget --no-cache -O - ${URLgithub}/bspwm/config/launch.sh > ~/.config/polybar/launch.sh
    chmod +x ~/.config/polybar/launch.sh
    rm ~/.config/polybar/config
    wget --no-cache -O - ${URLgithub}/bspwm/config/config > ~/.config/polybar/config

    #bspwmrc
    echo "${I_OK}    Creating bspwmrc config file"
    rm ~/.config/bspwm/bspwmrc
    wget --no-cache -O - ${URLgithub}/bspwm/config/bspwmrc > ~/.config/bspwm/bspwmrc
    chmod +x ~/.config/bspwm/bspwmrc

    #sxhkdrc
    echo "${I_OK}    Creating sxhkdrc config file"
    rm ~/.config/sxhkd/sxhkdrc
    wget --no-cache -O - ${URLgithub}/bspwm/config/sxhkdrc > ~/.config/sxhkd/sxhkdrc

    #picom.conf
    echo "${I_OK}    Creating picom.conf config file"
    rm ~/.config/picom/picom.conf
    wget --no-cache -O - ${URLgithub}/bspwm/config/picom.conf > ~/.config/picom/picom.conf
    rm ~/.config/picom/_picom.conf
    wget --no-cache -O - ${URLgithub}/bspwm/config/_picom.conf > ~/.config/picom/_picom.conf

    #config.rasi
    echo "${I_OK}    Creating rofi config file"
    rm ~/.config/rofi/config.rasi
    wget --no-cache -O - ${URLgithub}/bspwm/config/config.rasi > ~/.config/rofi/config.rasi

    #.Xresources
    rm ~/.Xresources
    wget --no-cache -O - ${URLgithub}/bspwm/config/Xresources > ~/.Xresources
    wget --no-cache -O - ${URLgithub}/bspwm/config/Xdefaults > ~/.Xdefaults
    wget --no-cache -O - ${URLgithub}/bspwm/config/bashrc > ~/.bashrc

    #.xinitrc
    rm ~/.xinitrc
    wget --no-cache -O - ${URLgithub}/bspwm/config/xinitrc > ~/.xinitrc

    # wallpapers
    sudo bash -c "wget --no-cache -O - ${URLgithub}/bspwm/motd > /etc/motd"
    wget --no-cache -O - ${URLgithub}/global/install-as-root | sudo bash
    # starting lightdm
    echo "${I_OK}    Starting lightdm"
    sudo rc-update add lightdm
    start-pulseaudio-x11
    sudo upgrade-system-reboot
fi