#!/bin/bash

setup-xorg-base 
echo bspwm setup script with lightdm
apk add bspwm sxhkd lightdm-gtk-greeter xterm feh picom setxkbmap font-ubuntu libva-glx rofi polybar ranger htop firefox xcalc
# Creates main config directory
echo Creating config directory
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/bashrc > /home/$(getent passwd 1000 | cut -d: -f1)/.bashrc
mkdir /home/$(getent passwd 1000 | cut -d: -f1)/.config
# Creates subdirectories
echo Creating bspwm, sxhkd, picom and polybar subdirectories
mkdir /home/$(getent passwd 1000 | cut -d: -f1)/.config/bspwm
mkdir /home/$(getent passwd 1000 | cut -d: -f1)/.config/sxhkd
mkdir /home/$(getent passwd 1000 | cut -d: -f1)/.config/picom
mkdir /home/$(getent passwd 1000 | cut -d: -f1)/.config/polybar
# Creates config files

#lightdm-gtk-greeter
echo Configuring lightdm-gtk-greeter
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/lightdm-gtk-greeter.conf > /etc/lightdm/lightdm-gtk-greeter.conf

#polybar
echo Creating polybar files
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/polybar/launch.sh
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/launch.sh > /home/$(getent passwd 1000 | cut -d: -f1)/.config/polybar/launch.sh
chmod +x /home/$(getent passwd 1000 | cut -d: -f1)/.config/polybar/launch.sh
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/polybar/config
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/config > /home/$(getent passwd 1000 | cut -d: -f1)/.config/polybar/config

#bspwmrc
echo Creating bspwmrc config file
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/bspwm/bspwmrc
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/bspwmrc > /home/$(getent passwd 1000 | cut -d: -f1)/.config/bspwm/bspwmrc
chmod +x /home/$(getent passwd 1000 | cut -d: -f1)/.config/bspwm/bspwmrc

#sxhkdrc
echo Creating sxhkdrc config file
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/sxhkd/sxhkdrc
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/sxhkdrc > /home/$(getent passwd 1000 | cut -d: -f1)/.config/sxhkd/sxhkdrc

#picom.conf
echo Creating picom.conf config file
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/picom/picom.conf
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/picom.conf > /home/$(getent passwd 1000 | cut -d: -f1)/.config/picom/picom.conf
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/picom/_picom.conf
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/_picom.conf > /home/$(getent passwd 1000 | cut -d: -f1)/.config/picom/_picom.conf

#.Xresources
rm /home/$(getent passwd 1000 | cut -d: -f1)/.Xresources
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/Xresources > /home/$(getent passwd 1000 | cut -d: -f1)/.Xresources
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/Xdefaults > /home/$(getent passwd 1000 | cut -d: -f1)/.Xdefaults

#.xinitrc
rm /home/$(getent passwd 1000 | cut -d: -f1)/.xinitrc
curl https://raw.githubusercontent.com/afimpel/alpine-linux/main/bspwm/config/xinitrc > /home/$(getent passwd 1000 | cut -d: -f1)/.xinitrc

# wallpapers
echo Downloading wallpapers
rm /home/$(getent passwd 1000 | cut -d: -f1)/.config/bspwm/wallpaper.jpg
curl -L https://raw.githubusercontent.com/afimpel/alpine-linux/main/assets/wallpaper.jpg?raw=true > /home/$(getent passwd 1000 | cut -d: -f1)/.config/bspwm/wallpaper.jpg
# starting lightdm
echo Starting lightdm
rc-update add lightdm
chown 1000:1000 /home/$(getent passwd 1000 | cut -d: -f1) -R
reboot
