#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID != 1000 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    sudo setup-xorg-base
    echo "${I_OK}    **** install packages ****" 
    wget --no-cache -O - ${URLgithub}/global/install-base-desktop | sudo bash
    wget --no-cache -O - ${URLgithub}/global/lightdm-as-root | sudo bash
    wget --no-cache -O - ${URLgithub}/global/install-base-desktop-apps | sudo bash

    sudo apk add --no-cache xfce4 xfce4-pulseaudio-plugin xfce4-whiskermenu-plugin-lang\
      xfce4-whiskermenu-plugin xfce4-notifyd tilix xfce4-notifyd-lang xfce4-pulseaudio-plugin-lang\
      xfce4-taskmanager xfce4-taskmanager-lang xfce4-power-manager-lang xfce4-panel-lang\
      thunar thunar-lang thunar-volman thunar-volman-lang xfce4-session-lang\
      networkmanager-wifi networkmanager-cli networkmanager networkmanager-lang network-manager-applet
    sudo adduser $(getent passwd 1000 | cut -d: -f1) audio
    sudo addgroup root audio

    sudo rc-update add dbus
    sudo rc-update add elogind
    sudo rc-update del networking boot
    sudo rc-update del wpa_supplicant boot
    sudo rc-update add networkmanager default

    echo "${I_OK}    **** application tweaks ****"
    mkdir -p ~/.config/xfce4/xfconf/xfce-perchannel-xml
    mkdir -p ~/.config/xfce4/panel/launcher-17
    mkdir -p ~/.config/xfce4/panel/launcher-18
    mkdir -p ~/.config/xfce4/panel/launcher-19
    mkdir -p ~/.config/xfce4/panel/launcher-20
    mkdir -p .local/share/xfce4/helpers/

    wget --no-cache -O - ${URLgithub}/global/install-as-user | bash
    wget --no-cache -O ~/.config/xfce4/helpers.rc ${URLgithub}/xfce4/config/helpers.rc
    wget --no-cache -O ~/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop ${URLgithub}/xfce4/helpers/custom-TerminalEmulator.desktop
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml ${URLgithub}/xfce4/config/xsettings.xml
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml ${URLgithub}/xfce4/config/keyboard-layout.xml 
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml ${URLgithub}/xfce4/config/xfce4-keyboard-shortcuts.xml 
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml ${URLgithub}/xfce4/config/xfce4-desktop.xml 
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml ${URLgithub}/xfce4/config/xfce4-panel.xml 
    cp /usr/share/applications/firefox.desktop ~/.config/xfce4/panel/launcher-17/firefox.desktop
    cp /usr/share/applications/com.gexperts.Tilix.desktop ~/.config/xfce4/panel/launcher-18/tilix.desktop
    cp /usr/share/applications/xfce4-file-manager.desktop ~/.config/xfce4/panel/launcher-19/xfce4-file-manager.desktop
    cp /usr/share/applications/org.xfce.mousepad.desktop ~/.config/xfce4/panel/launcher-20/org.xfce.mousepad.desktop
    chmod 777 -Rv ~/.config/xfce4/panel/launcher-*

    sudo echo "Desktop: XFCE4" >> /etc/motd
    wget --no-cache -O - ${URLgithub}/global/install-as-root | sudo bash
    echo "${I_OK}    **** cleanup ****"
    rm -rvf /config/.cache/* /tmp/*
    start-pulseaudio-x11
    sudo upgrade-system-reboot
fi