#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID != 1000 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    sudo setup-xorg-base
    echo "${I_OK}    **** install packages ****" 
    sudo apk add --no-cache xfce4 xfce4-pulseaudio-plugin xfce4-whiskermenu-plugin-lang  xfce4-whiskermenu-plugin xfce4-notifyd  xfce4-notifyd-lang xfce4-pulseaudio-plugin-lang xfce4-taskmanager xfce4-taskmanager-lang xfce4-power-manager-lang xfce4-panel-lang\
        xterm lightdm-gtk-greeter lightdm-gtk-greeter-lang mint-y-theme mint-y-icons dbus elogind polkit-elogind gvfs udisks2 mousepad mousepad-lang xcalc rofi dmenu font-fira-code font-ubuntu\
        pulseaudio pulseaudio-alsa alsa-plugins-pulse pulseaudio-utils pavucontrol networkmanager-wifi networkmanager networkmanager-lang network-manager-applet firefox thunar-lang 

    sudo adduser $(getent passwd 1000 | cut -d: -f1) audio
    sudo addgroup root audio

    sudo rc-update add dbus
    sudo rc-update add lightdm
    sudo rc-update add elogind
    sudo rc-update del networking boot
    sudo rc-update del wpa_supplicant boot
    sudo rc-update add networkmanager default

    echo "${I_OK}    **** application tweaks ****"
    mkdir -p ~/.config/xfce4/xfconf/xfce-perchannel-xml
    mkdir -p ~/.config/xfce4/panel/launcher-17
    mkdir -p ~/.config/xfce4/panel/launcher-18
    mkdir -p ~/.config/xfce4/panel/launcher-19
    mkdir -p ~/.config/xfce4/panel/launcher-20
    mkdir -p .local/share/xfce4/helpers/

    wget --no-cache -O - ${URLgithub}/global/install-as-user | bash
    wget --no-cache -O ~/.config/xfce4/helpers.rc ${URLgithub}/xfce4/config/helpers.rc
    wget --no-cache -O ~/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop ${URLgithub}/xfce4/config/custom-TerminalEmulator.desktop
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml ${URLgithub}/xfce4/config/xsettings.xml
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml ${URLgithub}/xfce4/config/xfce4-keyboard-shortcuts.xml 
    wget --no-cache -O ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml ${URLgithub}/xfce4/config/xfce4-panel.xml 
    wget --no-cache -O ~/.config/xfce4/panel/launcher-17/firefox.desktop ${URLgithub}/xfce4/config/panel/launcher-17/firefox.desktop
    wget --no-cache -O ~/.config/xfce4/panel/launcher-18/xfce4-terminal-emulator.desktop ${URLgithub}/xfce4/config/panel/launcher-18/xfce4-terminal-emulator.desktop 
    wget --no-cache -O ~/.config/xfce4/panel/launcher-19/xfce4-file-manager.desktop ${URLgithub}/xfce4/config/panel/launcher-19/xfce4-file-manager.desktop
    wget --no-cache -O ~/.config/xfce4/panel/launcher-20/org.xfce.mousepad.desktop ${URLgithub}/xfce4/config/panel/launcher-20/org.xfce.mousepad.desktop
    chmod 777 ~/.config/xfce4/panel/launcher-* -R

    sudo wget --no-cache -O /etc/motd ${URLgithub}/xfce4/motd
    wget --no-cache -O - ${URLgithub}/global/install-as-root | sudo bash
    echo "${I_OK}    **** cleanup ****"
    rm -rf /config/.cache/* /tmp/*
    start-pulseaudio-x11
    sudo upgrade-system-reboot
fi