#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID == 0 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    sudo setup-desktop gnome 
    echo "${I_OK}    **** install packages ****" 
    sudo apk add --no-cache \
        pulseaudio pulseaudio-alsa alsa-plugins-pulse pulseaudio-utils pavucontrol networkmanager network-manager-applet firefox  elogind polkit-elogind gvfs udisks2 xterm lightdm-gtk-greeter gnome-apps-core gnome-control-center gnome-backgrounds

    sudo rc-update add dbus
    sudo rc-update add lightdm
    sudo rc-update add elogind
    sudo rc-update del networking boot
    sudo rc-update del wpa_supplicant boot
    sudo rc-update add networkmanager
    sudo rc-update add openrc-settingsd default
    sudo rc-update add apk-polkit-server default

    echo "${I_OK}    **** application tweaks ****"
    curl -H 'Pragma: no-cache' -s ${URLgithub}/global/install-as-user | bash

    sudo bash -c "curl -H 'Pragma: no-cache' -L ${URLgithub}/gnome/motd > /etc/motd"
    curl -H 'Pragma: no-cache' -s ${URLgithub}/global/install-as-root | sudo bash

    echo "${I_OK}    **** cleanup ****"
    rm -rf /config/.cache/* /tmp/*
    start-pulseaudio-x11
    sudo upgrade-system-reboot
fi