#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID != 1000 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    echo "${I_OK}    Install Flatpak ..."
    sudo  apk add flatpak
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    wget --no-cache -O ~/flathub.desktop ${URLgithub}/utils/flathub.desktop
    sudo wget --no-cache -O /usr/share/applications/flathub.desktop ${URLgithub}/utils/flathub.desktop
    sudo wget --no-cache -O /usr/share/pixmaps/flathub.png ${URLgithub}/utils/flathub.png
    sudo chmod 777 /usr/share/pixmaps/* -R
    sudo chmod 777 ~/*.desktop -R
    sudo chmod 777 /var/lib/flatpak/exports/share/ -R
    sudo chmod 777 /usr/share/applications/flathub.desktop -R
    ln -s /var/lib/flatpak/exports/share/icons ~/.local/share/icons
    ln -s /var/lib/flatpak/exports/share/applications ~/.local/share/applications
    flatpak install flathub com.github.tchx84.Flatseal -y
    sudo upgrade-system-reboot
fi