#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"

if [ $UUID == 0 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    sudo setup-xorg-base 
    echo "${I_OK}    **** install packages ****" 
    sudo apk add --no-cache \
        kde-gtk-config khotkeys kmenuedit plasma kde-applications-multimedia plasma-browser-integration plasma-desktop plasma-systemmonitor plasma-workspace-wallpapers systemsettings \
        dolphin konsole kwrite breeze breeze-gtk breeze-icons util-linux-misc \
        firefox xterm lightdm-gtk-greeter dbus elogind polkit-elogind gvfs udisks2 pulseaudio alsa-plugins-pulse pulseaudio-alsa pulseaudio-utils pavucontrol rofi 

    sudo rc-update add dbus
    sudo rc-update add lightdm
    sudo rc-update add elogind
    sudo rc-update del networking boot
    sudo rc-update del wpa_supplicant boot
    sudo rc-update add networkmanager

    echo "${I_OK}    **** application tweaks ****"
    curl -H 'Pragma: no-cache' -s https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/install-as-user | bash

    echo "${I_OK}    **** kde tweaks ****"
    sudo sed -i \
        's/applications:org.kde.discover.desktop,/applications:org.kde.konsole.desktop,/g' \
        /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
    sudo su
    adduser $(getent passwd 1000 | cut -d: -f1) plugdev
    curl -H 'Pragma: no-cache' https://raw.githubusercontent.com/afimpel/alpine-linux/master/kde-plasma/motd > /etc/motd
    curl -H 'Pragma: no-cache' -s https://raw.githubusercontent.com/afimpel/alpine-linux/master/global/install-as-root | bash
    echo "${I_OK}    **** cleanup ****"
    rm -rf /config/.cache/* /tmp/*
    exit
    start-pulseaudio-x11
    sudo upgrade-system-reboot
fi