#!/bin/bash
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
URLgithub="https://raw.githubusercontent.com/afimpel/alpine-linux/master"

if [ $UUID != 1000 ]; then
    echo "${I_KO}    Start the Script as '$(getent passwd 1000 | cut -d: -f1)' for it to work properly    ${I_KO}";
    exit 1;
else
    sudo setup-xorg-base 
    echo "${I_OK}    **** install packages ****" 
    wget --no-cache -O - ${URLgithub}/global/install-base-desktop | sudo bash
    sudo apk add --no-cache \
        kde-gtk-config khotkeys kmenuedit plasma kde-applications-multimedia plasma-browser-integration plasma-desktop plasma-desktop-lang plasma-systemmonitor plasma-workspace-wallpapers systemsettings \
        dolphin dolphin-lang konsole kwrite konsole-lang kwrite-lang breeze breeze-gtk breeze-icons util-linux-misc

    sudo rc-update add dbus
    sudo rc-update add lightdm
    sudo rc-update add elogind
    sudo rc-update del networking boot
    sudo rc-update del wpa_supplicant boot
    sudo rc-update add networkmanager

    echo "${I_OK}    **** application tweaks ****"
    wget --no-cache -O - ${URLgithub}/global/install-as-user | bash

    echo "${I_OK}    **** kde tweaks ****"
    sudo sed -i \
        's/applications:org.kde.discover.desktop,/applications:org.kde.konsole.desktop,/g' \
        /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml

    sudo wget --no-cache -O /etc/motd ${URLgithub}/kde-plasma/motd
    wget --no-cache -O - ${URLgithub}/global/lightdm-as-root | sudo bash
    wget --no-cache -O - ${URLgithub}/global/install-as-root | sudo bash

    echo "${I_OK}    **** cleanup ****"
    rm -rf /config/.cache/* /tmp/*
    start-pulseaudio-x11
    sudo upgrade-system-reboot
fi